"""Add transit inventory

Revision ID: 99ff191b5f7d
Revises: 11e74f3503d2
Create Date: 2026-07-07 16:05:23.699399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '99ff191b5f7d'
down_revision: Union[str, Sequence[str], None] = '11e74f3503d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('drug_masters', 'initial_quantity',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('indents', 'dispatched_qty',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('indents', 'dispatched_batch_no',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('indents', 'courier_details',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('indents', 'dispatch_remarks',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('indents', 'service_area_code',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_constraint(op.f('fk_indents_drug_id'), 'indents', type_='foreignkey')
    op.create_foreign_key(None, 'indents', 'drug_masters', ['drug_id'], ['id'])
    op.alter_column('shift_logs', 'sent_back_qty',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.drop_column('shift_logs', 'damaged_qty')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shift_logs', sa.Column('damaged_qty', mysql.DOUBLE(asdecimal=True), server_default=sa.text("'0'"), nullable=True))
    op.alter_column('shift_logs', 'sent_back_qty',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.drop_constraint(None, 'indents', type_='foreignkey')
    op.create_foreign_key(op.f('fk_indents_drug_id'), 'indents', 'drug_masters', ['drug_id'], ['id'], ondelete='SET NULL')
    op.alter_column('indents', 'service_area_code',
               existing_type=sa.String(length=50),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('indents', 'dispatch_remarks',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('indents', 'courier_details',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('indents', 'dispatched_batch_no',
               existing_type=sa.String(length=100),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('indents', 'dispatched_qty',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
    op.alter_column('drug_masters', 'initial_quantity',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
    # ### end Alembic commands ###
