"""Add transit inventory

Revision ID: 99ff191b5f7d
Revises: 11e74f3503d2
Create Date: 2026-07-07 16:05:23.699399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '99ff191b5f7d'
down_revision: Union[str, Sequence[str], None] = '11e74f3503d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_approval_configs_id'), table_name='project_approval_configs')
    op.drop_index(op.f('ix_project_approval_configs_project_name'), table_name='project_approval_configs')
    op.drop_table('project_approval_configs')
    op.drop_index(op.f('ix_role_permissions_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_project'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_role'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.alter_column('drug_masters', 'initial_quantity',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('indents', 'dispatched_qty',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('indents', 'dispatched_batch_no',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('indents', 'courier_details',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('indents', 'dispatch_remarks',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('indents', 'service_area_code',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_constraint(op.f('fk_indents_drug_id'), 'indents', type_='foreignkey')
    op.create_foreign_key(None, 'indents', 'drug_masters', ['drug_id'], ['id'])
    op.alter_column('shift_logs', 'sent_back_qty',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.drop_column('shift_logs', 'damaged_qty')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shift_logs', sa.Column('damaged_qty', mysql.DOUBLE(asdecimal=True), server_default=sa.text("'0'"), nullable=True))
    op.alter_column('shift_logs', 'sent_back_qty',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.drop_constraint(None, 'indents', type_='foreignkey')
    op.create_foreign_key(op.f('fk_indents_drug_id'), 'indents', 'drug_masters', ['drug_id'], ['id'], ondelete='SET NULL')
    op.alter_column('indents', 'service_area_code',
               existing_type=sa.String(length=50),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('indents', 'dispatch_remarks',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('indents', 'courier_details',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('indents', 'dispatched_batch_no',
               existing_type=sa.String(length=100),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('indents', 'dispatched_qty',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
    op.alter_column('drug_masters', 'initial_quantity',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
    op.create_table('role_permissions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('role', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('page', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('can_view', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('can_create', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('can_update', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('can_delete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('project', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_role_permissions_role'), 'role_permissions', ['role'], unique=False)
    op.create_index(op.f('ix_role_permissions_project'), 'role_permissions', ['project'], unique=False)
    op.create_index(op.f('ix_role_permissions_id'), 'role_permissions', ['id'], unique=False)
    op.create_table('project_approval_configs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('skip_roles', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('stop_role', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_project_approval_configs_project_name'), 'project_approval_configs', ['project_name'], unique=True)
    op.create_index(op.f('ix_project_approval_configs_id'), 'project_approval_configs', ['id'], unique=False)
    # ### end Alembic commands ###
