"""add_bag_columns_to_shift_log

Revision ID: 9b1bb8cca5ac
Revises: a2661c8a0b84
Create Date: 2026-07-12 17:43:21.841635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9b1bb8cca5ac'
down_revision: Union[str, Sequence[str], None] = 'a2661c8a0b84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shift_logs', sa.Column('drawn_qty', sa.Float(), nullable=False))
    op.add_column('shift_logs', sa.Column('bag_ob', sa.Float(), nullable=False))
    op.add_column('shift_logs', sa.Column('bag_received', sa.Float(), nullable=False))
    op.add_column('shift_logs', sa.Column('bag_sent_back', sa.Float(), nullable=False))
    op.add_column('shift_logs', sa.Column('bag_consumed', sa.Float(), nullable=False))
    op.add_column('shift_logs', sa.Column('bag_closing', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shift_logs', 'bag_closing')
    op.drop_column('shift_logs', 'bag_consumed')
    op.drop_column('shift_logs', 'bag_sent_back')
    op.drop_column('shift_logs', 'bag_received')
    op.drop_column('shift_logs', 'bag_ob')
    op.drop_column('shift_logs', 'drawn_qty')
    # ### end Alembic commands ###
