"""add_drawn_qty_to_transit_inventory

Revision ID: a2661c8a0b84
Revises: 99ff191b5f7d
Create Date: 2026-07-12 17:28:32.403144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a2661c8a0b84'
down_revision: Union[str, Sequence[str], None] = '99ff191b5f7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transit_inventories', sa.Column('drawn_qty', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transit_inventories', 'drawn_qty')
    # ### end Alembic commands ###
