"""add_drawn_qty_to_transit_inventory

Revision ID: a2661c8a0b84
Revises: 99ff191b5f7d
Create Date: 2026-07-12 17:28:32.403144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a2661c8a0b84'
down_revision: Union[str, Sequence[str], None] = '99ff191b5f7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roster_lookup'), table_name='shift_rosters')
    op.drop_index(op.f('ix_shift_rosters_employee_code'), table_name='shift_rosters')
    op.drop_index(op.f('ix_shift_rosters_id'), table_name='shift_rosters')
    op.drop_index(op.f('ix_shift_rosters_office_name'), table_name='shift_rosters')
    op.drop_index(op.f('ix_shift_rosters_project'), table_name='shift_rosters')
    op.drop_index(op.f('ix_shift_rosters_shift_date'), table_name='shift_rosters')
    op.drop_index(op.f('ix_shift_rosters_status'), table_name='shift_rosters')
    op.drop_index(op.f('uq_roster_assignment'), table_name='shift_rosters')
    op.drop_table('shift_rosters')
    op.drop_index(op.f('ix_role_permissions_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_project'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_role'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_project_approval_configs_id'), table_name='project_approval_configs')
    op.drop_index(op.f('ix_project_approval_configs_project_name'), table_name='project_approval_configs')
    op.drop_table('project_approval_configs')
    op.add_column('transit_inventories', sa.Column('drawn_qty', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transit_inventories', 'drawn_qty')
    op.create_table('project_approval_configs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('skip_roles', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('stop_role', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('low_stock_threshold', mysql.INTEGER(), server_default=sa.text("'10'"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_project_approval_configs_project_name'), 'project_approval_configs', ['project_name'], unique=True)
    op.create_index(op.f('ix_project_approval_configs_id'), 'project_approval_configs', ['id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('role', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('page', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('can_view', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('can_create', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('can_update', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('can_delete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('project', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_role_permissions_role'), 'role_permissions', ['role'], unique=False)
    op.create_index(op.f('ix_role_permissions_project'), 'role_permissions', ['project'], unique=False)
    op.create_index(op.f('ix_role_permissions_id'), 'role_permissions', ['id'], unique=False)
    op.create_table('shift_rosters',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('office_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('employee_code', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('employee_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('shift_date', sa.DATE(), nullable=False),
    sa.Column('shift_type', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('start_time', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('end_time', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('created_by', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('remarks', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('uq_roster_assignment'), 'shift_rosters', ['employee_code', 'shift_date', 'shift_type', 'project'], unique=True)
    op.create_index(op.f('ix_shift_rosters_status'), 'shift_rosters', ['status'], unique=False)
    op.create_index(op.f('ix_shift_rosters_shift_date'), 'shift_rosters', ['shift_date'], unique=False)
    op.create_index(op.f('ix_shift_rosters_project'), 'shift_rosters', ['project'], unique=False)
    op.create_index(op.f('ix_shift_rosters_office_name'), 'shift_rosters', ['office_name'], unique=False)
    op.create_index(op.f('ix_shift_rosters_id'), 'shift_rosters', ['id'], unique=False)
    op.create_index(op.f('ix_shift_rosters_employee_code'), 'shift_rosters', ['employee_code'], unique=False)
    op.create_index(op.f('ix_roster_lookup'), 'shift_rosters', ['employee_code', 'shift_date', 'project'], unique=False)
    # ### end Alembic commands ###
