"""add_project_shifts_and_calendar

Revision ID: d1e33a3bb762
Revises: 064e53e69acc
Create Date: 2026-07-22 16:12:15.518455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1e33a3bb762'
down_revision: Union[str, Sequence[str], None] = '064e53e69acc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_calendar_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=100), nullable=False),
    sa.Column('weekoff_days', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_calendar_configs_id'), 'project_calendar_configs', ['id'], unique=False)
    op.create_index(op.f('ix_project_calendar_configs_project_name'), 'project_calendar_configs', ['project_name'], unique=True)
    op.create_table('project_holidays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=100), nullable=False),
    sa.Column('holiday_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_name', 'holiday_date', name='uq_project_holiday_date')
    )
    op.create_index(op.f('ix_project_holidays_id'), 'project_holidays', ['id'], unique=False)
    op.create_index(op.f('ix_project_holidays_project_name'), 'project_holidays', ['project_name'], unique=False)
    op.create_table('project_shift_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=100), nullable=False),
    sa.Column('shift_type', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('default_start', sa.String(length=10), nullable=True),
    sa.Column('default_end', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_name', 'shift_type', name='uq_project_shift')
    )
    op.create_index(op.f('ix_project_shift_mappings_id'), 'project_shift_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_project_shift_mappings_project_name'), 'project_shift_mappings', ['project_name'], unique=False)
    op.drop_index(op.f('idx_audit_logs_perf'), table_name='audit_logs')
    op.drop_index(op.f('idx_indents_perf'), table_name='indents')
    op.drop_index(op.f('idx_shift_logs_perf'), table_name='shift_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_shift_logs_perf'), 'shift_logs', ['project', 'office_name', 'date'], unique=False)
    op.create_index(op.f('idx_indents_perf'), 'indents', ['project', 'office_name', 'status'], unique=False)
    op.create_index(op.f('idx_audit_logs_perf'), 'audit_logs', ['timestamp', 'project'], unique=False)
    op.drop_index(op.f('ix_project_shift_mappings_project_name'), table_name='project_shift_mappings')
    op.drop_index(op.f('ix_project_shift_mappings_id'), table_name='project_shift_mappings')
    op.drop_table('project_shift_mappings')
    op.drop_index(op.f('ix_project_holidays_project_name'), table_name='project_holidays')
    op.drop_index(op.f('ix_project_holidays_id'), table_name='project_holidays')
    op.drop_table('project_holidays')
    op.drop_index(op.f('ix_project_calendar_configs_project_name'), table_name='project_calendar_configs')
    op.drop_index(op.f('ix_project_calendar_configs_id'), table_name='project_calendar_configs')
    op.drop_table('project_calendar_configs')
    # ### end Alembic commands ###
