"""create_api_settings_table

Revision ID: fa4231c8c929
Revises: fa1309b46e16
Create Date: 2026-07-15 15:10:28.793649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa4231c8c929'
down_revision: Union[str, Sequence[str], None] = 'fa1309b46e16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_identifier', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=False),
    sa.Column('auth_type', sa.String(length=50), nullable=False),
    sa.Column('encrypted_auth_data', sa.String(length=1000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_settings_api_identifier'), 'api_settings', ['api_identifier'], unique=True)
    op.create_index(op.f('ix_api_settings_id'), 'api_settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_settings_id'), table_name='api_settings')
    op.drop_index(op.f('ix_api_settings_api_identifier'), table_name='api_settings')
    op.drop_table('api_settings')
    # ### end Alembic commands ###
